# Generated by Django 5.2.5 on 2025-09-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likeDate',
        ),
    ]
